---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: payment
  labels:
    name: payment
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        name: payment
    spec:
      containers:
      - name: payment
        image: weaveworksdemos/payment:0.4.3
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        {{- if .Values.zipkin.enabled }}
        env:
        - name: ZIPKIN
          value: http://{{ .Values.zipkin.url }}:9411/api/v1/spans
        {{- end }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
