---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front-end
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        name: front-end
    spec:
      containers:
      - name: front-end
        image: 172.16.1.13/front-end/front-end:20 
        resources:
          limits:
            cpu: 300m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 300Mi
        ports:
        - containerPort: 8079
        env:
        - name: SESSION_REDIS
          value: "true"
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
          readOnlyRootFilesystem: true
